# Generated by Django 3.2.9 on 2022-03-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20220305_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
    ]
