# Generated by Django 3.2.9 on 2022-03-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraddress_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescueservices',
            options={'verbose_name': 'Rescue Service', 'verbose_name_plural': 'Rescue servies'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Adresses'},
        ),
    ]
