# Generated by Django 3.2.9 on 2022-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220306_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.TextField(default='Some Rich Text'),
        ),
    ]
