# Generated by Django 3.2.9 on 2022-03-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_description',
        ),
    ]
